CREATE TABLE [dbo].[M_USERS]
(
	[UID] INT NOT NULL PRIMARY KEY,
    [FIRSTNAME] NCHAR(20) NOT NULL, 
    [LASTNAME] NCHAR(20) NOT NULL, 
    [EMAIL] NVARCHAR(255) NOT NULL, 
    [PASSWORD] NCHAR(40) NOT NULL, 
    [ROLEID] SMALLINT NOT NULL, 
	CONSTRAINT [FK_M_USERS_M_USERROLE] FOREIGN KEY ([ROLEID]) REFERENCES [M_USERROLE]([RID])
)
