INSERT [dbo].[M_USERROLE] ([RID], [ROLE_NAME]) VALUES (1, N'User')
INSERT [dbo].[M_USERROLE] ([RID], [ROLE_NAME]) VALUES (2, N'Moderator')
INSERT [dbo].[M_USERROLE] ([RID], [ROLE_NAME]) VALUES (3, N'Admin')